apiVersion: v1
kind: Secret
metadata:
  name: airflow-env
type: Opaque
data:
  mysqlUser: YWlyZmxvdw==
  mysqlPassword: YWlyZmxvd2d4MTIzNA==
  smtpPassword: QkJYRnNuSGdBRXNFbDh5Tng2dUJ0VVFDRnJpaWQxZjZTaHVaRzRLUUU0dVg=